<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>InternetHealth.Core</RootNamespace>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="InternetHealth.Core.Tests" />
  </ItemGroup>
</Project>
